# Generated by Django 5.2.17 on 2026-09-20 16:15

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Create subscriber, search, rate-limit, and postcode reference tables."""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Capacity",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequestSource",
            fields=[
                ("key", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("day", models.DateField()),
                ("count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("suppressed", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(null=True)),
                ("email_day", models.DateField(null=True)),
                ("email_count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Postcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=4)),
                ("state", models.CharField(max_length=3)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("code", "state"), name="postcode_state")
                ],
            },
        ),
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=300)),
                ("postcode", models.CharField(max_length=4)),
                ("state", models.CharField(max_length=3)),
                ("interstate", models.BooleanField()),
                ("status", models.CharField(default="pending", max_length=10)),
                ("created_at", models.DateTimeField()),
                ("activated_at", models.DateTimeField(null=True)),
                ("expires_at", models.DateTimeField(null=True)),
                ("cancelled_at", models.DateTimeField(null=True)),
                ("confirmation_version", models.UUIDField(default=uuid.uuid4)),
                ("management_version", models.UUIDField(default=uuid.uuid4)),
                ("baseline_pending", models.BooleanField(default=True)),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="searches",
                        to="subscriptions.subscriber",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "expires_at"], name="subscriptio_status_55d6e5_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["pending", "active", "cancelled"])),
                        name="valid_search_status",
                    )
                ],
            },
        ),
    ]
