#!/bin/zsh
# Daily-refresh launcher for the Sydney dog-finder.
# Invoked by launchd (com.dog-finder.daily-refresh) at 21:00 local time.
# Lives outside ~/Documents so the launchd agent isn't blocked by macOS TCC.
#
# Each run gets a folder runs/<ts>/ holding: the deterministic pipeline output
# (candidates.json + fetch_manifest.json), the full LLM event stream
# (run.stream.jsonl), and the readable report (report.txt).
#
# Flow: a stdlib Python pipeline does fetch/parse/dedup for static PetRescue
# shelters FIRST, then the LLM judges the resulting candidates and drives the
# browser MCP for the JS/own-site shelters the pipeline flagged NEEDS_BROWSER.
#
# Captures usage two ways:
#   Tier 1 (aggregate + per-model): parsed from the final result event into logs/usage.log
#   Tier 2 (full event stream):     saved to runs/<ts>/run.stream.jsonl for per-subagent analysis
# The agent prompt is extracted live from prompts/daily-refresh.md (everything
# after the first "---" line) so that file stays the single source of truth.

DIR="$HOME/Code/dog-finder"
PROMPT_FILE="$DIR/prompts/daily-refresh.md"
LOG="$DIR/logs/daily-refresh.log"
USAGE_LOG="$DIR/logs/usage.log"
RUNS="$DIR/runs"

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
mkdir -p "$RUNS" "$DIR/logs"
cd "$DIR" || { echo "$(date '+%F %T %Z') FATAL: cannot cd to $DIR" >> "$LOG"; exit 1; }

TS="$(date '+%Y%m%d-%H%M%S')"
RUNDIR="$RUNS/$TS"
mkdir -p "$RUNDIR"
STREAM="$RUNDIR/run.stream.jsonl"
REPORT="$RUNDIR/report.txt"
CANDIDATES="$RUNDIR/candidates.json"
MANIFEST="$RUNDIR/fetch_manifest.json"

echo "===== run started $(date '+%F %T %Z') (ts=$TS) =====" >> "$LOG"

PROMPT="$(awk 'f; /^---$/{f=1}' "$PROMPT_FILE")"
if [ -z "$PROMPT" ]; then
  echo "$(date '+%F %T %Z') FATAL: empty prompt extracted from $PROMPT_FILE" >> "$LOG"
  exit 1
fi

# Phase 2: run the deterministic fetch/parse/dedup pipeline before the LLM.
# Non-fatal: if it fails, the LLM still runs and can fall back to the browser path.
echo "$(date '+%F %T %Z') running pipeline -> $RUNDIR" >> "$LOG"
/usr/bin/python3 -m src.pipeline \
  --shelters "$DIR/config/shelters.json" \
  --index "$DIR/data/dog-index.md" \
  --out "$RUNDIR" >> "$LOG" 2>&1 \
  || echo "$(date '+%F %T %Z') WARN: pipeline exited non-zero; LLM proceeds with whatever artifacts exist" >> "$LOG"

# Hand the LLM this run's artifact paths so it judges instead of re-scraping.
PROMPT="$PROMPT

## This run's artifacts (already generated by the launcher)
- candidates: $CANDIDATES
- manifest:   $MANIFEST"

# Tier 2: full event stream -> STREAM ; human-readable progress/errors -> LOG
/usr/local/bin/claude -p "$PROMPT" \
  --model sonnet \
  --dangerously-skip-permissions \
  --max-budget-usd 2.5 \
  --output-format stream-json --verbose > "$STREAM" 2>>"$LOG"
CODE=$?

# Tier 1: parse the final result event for aggregate + per-model usage.
python3 "$DIR/src/parse_usage.py" "$STREAM" "$REPORT" "$TS" "$CODE" >> "$USAGE_LOG" 2>>"$LOG"

# Mirror the readable report into the main log if we got one.
if [ -s "$REPORT" ]; then
  echo "--- report (ts=$TS) ---" >> "$LOG"
  cat "$REPORT" >> "$LOG"
fi

echo "===== run finished $(date '+%F %T %Z') (exit $CODE) =====" >> "$LOG"
exit $CODE
