#!/bin/zsh
# Daily-refresh launcher for the Sydney dog-finder.
# Invoked by launchd (com.dog-finder.daily-refresh) at 13:00 local time.
# Lives outside ~/Documents so the launchd agent isn't blocked by macOS TCC.
#
# Each run gets a folder runs/<ts>/ holding: the deterministic pipeline output
# (pending.json + fetch_manifest.json), the LLM's verdicts.json, the full event
# stream (run.stream.jsonl), and the readable report (report.txt).
#
# Flow: a stdlib Python pipeline does fetch/parse/dedup for static PetRescue
# shelters FIRST, then the LLM judges the resulting candidates and drives the
# browser MCP for the JS/own-site shelters the pipeline flagged NEEDS_BROWSER.
#
# Captures usage two ways:
#   Tier 1 (aggregate + per-model): parsed from the final result event into logs/usage.log
#   Tier 2 (full event stream):     saved to runs/<ts>/run.stream.jsonl for per-subagent analysis
# The agent prompt is extracted live from prompts/daily-refresh.md (everything
# after the first "---" line) so that file stays the single source of truth.

DIR="$HOME/Code/dog-finder"
PROMPT_FILE="$DIR/prompts/daily-refresh.md"
LOG="$DIR/logs/daily-refresh.log"
USAGE_LOG="$DIR/logs/usage.log"
RUNS="$DIR/runs"

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
mkdir -p "$RUNS" "$DIR/logs"
cd "$DIR" || { echo "$(date '+%F %T %Z') FATAL: cannot cd to $DIR" >> "$LOG"; exit 1; }

# Overlap lock: a mkdir on a directory is atomic, so it doubles as a mutex. If
# a run is still alive when the next 13:00 slot fires, skip this slot rather
# than corrupting state with two concurrent writers. A lock older than 4 hours
# is assumed left behind by a crashed run (the watchdog caps a healthy run well
# under that) and is broken and retaken.
LOCK="$DIR/.run.lock"
if ! mkdir "$LOCK" 2>/dev/null; then
  # Hardcode /usr/bin/stat (BSD syntax): a GNU stat earlier on PATH would reject
  # -f and misread every held lock as stale, breaking a live run's lock.
  LOCK_AGE=$(( $(date +%s) - $(/usr/bin/stat -f %m "$LOCK" 2>/dev/null || echo 0) ))
  if [ "$LOCK_AGE" -gt 14400 ]; then
    echo "$(date '+%F %T %Z') WARN: run lock older than 4h; treating as stale and retaking" >> "$LOG"
    rmdir "$LOCK" 2>/dev/null
    if ! mkdir "$LOCK" 2>/dev/null; then
      echo "$(date '+%F %T %Z') another run holds the lock; skipping" >> "$LOG"
      exit 0
    fi
  else
    echo "$(date '+%F %T %Z') another run holds the lock; skipping" >> "$LOG"
    exit 0
  fi
fi
trap 'rmdir "$LOCK" 2>/dev/null' EXIT

TS="$(date '+%Y%m%d-%H%M%S')"
RUNDIR="$RUNS/$TS"
mkdir -p "$RUNDIR"
STREAM="$RUNDIR/run.stream.jsonl"
REPORT="$RUNDIR/report.txt"
PENDING="$RUNDIR/pending.json"
MANIFEST="$RUNDIR/fetch_manifest.json"
VERDICTS="$RUNDIR/verdicts.json"
STATE="$DIR/data/state.json"
INDEX="$DIR/data/dog-index.md"

echo "===== run started $(date '+%F %T %Z') (ts=$TS) =====" >> "$LOG"

PROMPT="$(awk 'f; /^---$/{f=1}' "$PROMPT_FILE")"
if [ -z "$PROMPT" ]; then
  echo "$(date '+%F %T %Z') FATAL: empty prompt extracted from $PROMPT_FILE" >> "$LOG"
  exit 1
fi

# Retention: drop state entries unseen for >90 days so state.json stays bounded.
echo "$(date '+%F %T %Z') prune stale state (>90d)" >> "$LOG"
/usr/bin/python3 -m src.pipeline prune --state "$STATE" --days 90 >> "$LOG" 2>&1 \
  || echo "$(date '+%F %T %Z') WARN: prune exited non-zero" >> "$LOG"

# Phase 2 collect: deterministic fetch/parse/dedup into state.json before the LLM.
# Non-fatal: if it fails, the LLM still runs and can fall back to the browser path.
echo "$(date '+%F %T %Z') collect -> $RUNDIR" >> "$LOG"
/usr/bin/python3 -m src.pipeline collect \
  --shelters "$DIR/config/shelters.json" \
  --state "$STATE" \
  --out "$RUNDIR" >> "$LOG" 2>&1 \
  || echo "$(date '+%F %T %Z') WARN: collect exited non-zero; LLM proceeds with whatever artifacts exist" >> "$LOG"

# Hand the LLM this run's artifact paths and tell it where to write its verdicts.
PROMPT="$PROMPT

## This run's artifacts (generated by the launcher)
- pending dogs to judge: $PENDING
- fetch manifest:        $MANIFEST
- WRITE YOUR VERDICTS to: $VERDICTS (a JSON array of {url, verdict, summary, tags, removed, ...}).
The launcher merges that file into state and re-renders the index after you finish; do NOT edit dog-index.md yourself."

# Tier 2: full event stream -> STREAM ; human-readable progress/errors -> LOG
#
# Run the judge under a watchdog. launchd will NOT start the next 13:00
# StartCalendarInterval run while this script is still alive, so a hung claude
# call (e.g. an unbounded API-retry spin) silently blocks every future run
# until the stuck process is killed by hand — exactly what happened on
# 2026-06-14. JUDGE_TIMEOUT caps the call so one bad run can't wedge the
# schedule. 5400s (90 min) is ~7x the slowest healthy judge step observed.
# --max-budget-usd bounds API spend but not a non-billable spin, so it is not a
# substitute for this wall-clock guard.
JUDGE_TIMEOUT=5400
echo "$(date '+%F %T %Z') invoking Claude (sonnet) to judge pending dogs; live tool activity in $STREAM" >> "$LOG"
/usr/local/bin/claude -p "$PROMPT" \
  --model sonnet \
  --dangerously-skip-permissions \
  --max-budget-usd 2.5 \
  --output-format stream-json --verbose > "$STREAM" 2>>"$LOG" &
CLAUDE_PID=$!
# Watchdog: if the judge outlives JUDGE_TIMEOUT, TERM (then KILL) it and its
# children so the script can finish and release the launchd slot. Exits quietly
# if the judge has already returned on its own.
(
  sleep "$JUDGE_TIMEOUT"
  kill -0 "$CLAUDE_PID" 2>/dev/null || exit 0
  echo "$(date '+%F %T %Z') WARN: judge exceeded ${JUDGE_TIMEOUT}s; killing pid $CLAUDE_PID and children" >> "$LOG"
  pkill -TERM -P "$CLAUDE_PID" 2>/dev/null
  kill -TERM "$CLAUDE_PID" 2>/dev/null
  sleep 10
  pkill -KILL -P "$CLAUDE_PID" 2>/dev/null
  kill -KILL "$CLAUDE_PID" 2>/dev/null
) &
WATCHDOG_PID=$!
wait "$CLAUDE_PID"
CODE=$?
# Judge finished (on its own or via the watchdog); cancel the watchdog if still sleeping.
kill "$WATCHDOG_PID" 2>/dev/null
wait "$WATCHDOG_PID" 2>/dev/null

# Fail loudly if the judge produced no verdicts at all (crash, auth failure, or
# a watchdog kill before it could write anything) — this is what silently
# recurred for 12 days during the 2026-06-22 auth outage, since nothing was
# watching the log. A file that exists but is empty/absent is the actual
# failure signal; a deliberate `[]` (nothing needed judging) is non-empty and
# is NOT treated as a failure. Fires a macOS notification since this agent
# runs in the user's GUI session and can post one directly.
if [ ! -s "$VERDICTS" ]; then
  echo "$(date '+%F %T %Z') FATAL: judge produced no verdicts (exit $CODE); see $STREAM" >> "$LOG"
  MSG="Judge produced no verdicts for run $TS (exit $CODE). Check logs/daily-refresh.log."
  osascript -e "display notification \"$MSG\" with title \"dog-finder daily refresh failed\" sound name \"Basso\"" \
    >> "$LOG" 2>&1 || echo "$(date '+%F %T %Z') WARN: notification failed to send" >> "$LOG"
fi

# Phase 2 apply: merge the LLM's verdicts into state and re-render the index.
# Tolerant of a missing verdicts.json (e.g. the LLM run failed) — apply just
# re-renders from existing state in that case.
echo "$(date '+%F %T %Z') apply verdicts -> $INDEX" >> "$LOG"
/usr/bin/python3 -m src.pipeline apply \
  --state "$STATE" \
  --verdicts "$VERDICTS" \
  --index "$INDEX" >> "$LOG" 2>&1 \
  || echo "$(date '+%F %T %Z') WARN: apply exited non-zero; index may be stale" >> "$LOG"

# Commit the index/state only when the dog list's membership CHANGED since the
# last commit (a dog was added or dropped). In-place edits that keep the same set
# of dogs stay local in the working tree, so commit history tracks the list's
# membership changes rather than every run.
# Only these two tracked files are staged; runs/ and logs/ stay gitignored.
if [ -n "$(git status --porcelain -- "$INDEX" "$STATE")" ]; then
  DECISION="$(/usr/bin/python3 -m src.pipeline index-check --index "$INDEX" 2>>"$LOG")"
  if [ "$DECISION" = "commit" ]; then
    git add "$INDEX" "$STATE"
    # Scope the commit to these two paths so anything a human left staged is
    # never swept into an automated commit.
    if git commit -m "Automated run on $(date '+%F')" -- "$INDEX" "$STATE" >> "$LOG" 2>&1; then
      echo "$(date '+%F %T %Z') committed index/state (dog list changed)" >> "$LOG"
      # Publish the commit so the GitHub copy tracks the local membership change.
      # Non-fatal: a push failure (e.g. no network) leaves the commit local for
      # the next run to push, and must not wedge the rest of the script.
      if git push >> "$LOG" 2>&1; then
        echo "$(date '+%F %T %Z') pushed commit to origin" >> "$LOG"
      else
        echo "$(date '+%F %T %Z') WARN: git push to origin failed" >> "$LOG"
      fi
    else
      echo "$(date '+%F %T %Z') WARN: git commit of index/state failed" >> "$LOG"
    fi
  else
    echo "$(date '+%F %T %Z') index changed but dog list unchanged; keeping changes local" >> "$LOG"
  fi
else
  echo "$(date '+%F %T %Z') no index/state changes" >> "$LOG"
fi

# Tier 1: parse the final result event for aggregate + per-model usage.
/usr/bin/python3 "$DIR/src/parse_usage.py" "$STREAM" "$REPORT" "$TS" "$CODE" >> "$USAGE_LOG" 2>>"$LOG"

# Mirror the readable report into the main log if we got one.
if [ -s "$REPORT" ]; then
  echo "--- report (ts=$TS) ---" >> "$LOG"
  cat "$REPORT" >> "$LOG"
fi

echo "===== run finished $(date '+%F %T %Z') (exit $CODE) =====" >> "$LOG"
exit $CODE
